# Generated by Django 3.1.6 on 2021-03-24 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('msp_current', models.IntegerField()),
                ('msp_past', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.IntegerField()),
                ('entrytime', models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 6, 2, 436622))),
                ('active', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.crops')),
            ],
        ),
    ]
