# Generated by Django 3.1.6 on 2021-03-24 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 13, 7, 279676)),
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastBid', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.crops')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.farmers')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.trader')),
            ],
        ),
    ]
