# Generated by Django 3.1.7 on 2021-03-25 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20210325_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 12, 29, 40, 168216)),
        ),
    ]
